### ISSUE TITLE
Make a more robust Travis CI configuration

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/pcdshub.github.io#10]
1. Build the documentation on all Travis runs but only push if on `pcdshub/source` branch.
2. If we fail to build the docs do not push to `pcds/master`.

**Comment by ZryletTC** [comment]
Part 2 can just be done with a `set -e` as noted in the warning [here](https://drdoctr.github.io/#edit-your-travis-file).

For Part 1, I believe we do this in pcdsdevices and other repos with [this](https://github.com/pcdshub/pcdsdevices/blob/6dd968b5bd323446b8ba13cd5190165df9bbdf16/.travis.yml#L105-L109):
```
  - |
    if [[ -n "$DOCTR_DEPLOY_ENCRYPTION_KEY_PCDSHUB_PCDSDEVICES" && $BUILD_DOCS ]]; then
      echo "Deploying docs"
      doctr deploy . --built-docs docs/build/html --deploy-branch-name gh-pages
    fi
```
although I don't understand how this doesn't run during every `BUILD_DOCS=1` run since the deploy key is defined at the top of the file. In short, I don't understand how the doctr deploy key works. @klauer do you?

**Comment by ZLLentz** [comment]
I think we should take care of these in `pcds-ci-helpers`

**Comment by klauer** [comment]
I think it's due to travis/doctr itself:

https://github.com/drdoctr/doctr

> Travis does not make secure environment variables available to pull requests builds. Furthermore, Doctr itself does not push from any branch other than master by default, although this :ref:`can be changed <any-branch>`.

**Comment by ZryletTC** [comment]
Thanks! Totally missed that.
